apiVersion: v1
data:
  SERVICE_PORT: 80
kind: ConfigMap
metadata:
  name: hello-world-config
  namespace: kaizen-hello-world-development
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 10m0s
  path: rancher-hello-world
  prune: true
  sourceRef:
    kind: GitRepository
    name: kaizen
  validation: client
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kaizen
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: dev
  url: https://github.com/kaizentm/gitops-manifests/
